markdown: kramdown
permalink: /:year/:month/:day/:title/
url: https://willingseal.github.io
author: willingseal
highlighter: rouge
exclude: ["Rakefile", "CNAME", "README.md"]
safe: false
paginate: 15


# Gems
gems: [jekyll-paginate]
